const libros = [
    { id: 1, nombre: "La Guerra de dos reinas", editorial: "PUNK", resumen: "La guerra es solo el principio... De la autora best seller del New York Times Jennifer L. Armentrout llega el cuarto libro de su saga De sangre y cenizas.", ISBN: "978-987-8977-14-0", imagen: "La guerra de dos reinas.png" },
    { id: 2, nombre: "Cuento de hadas", editorial: "Plaza & Janes", resumen: "Stephen King regresa a la fantasía por todo lo alto con una novela magnífica sobre un inesperado héroe que deberá tomar parte en la épica batalla entre el bien y el mal. Bienvenidos al lado oscuro De érase una vez.", ISBN: "978-950-644-643-7", imagen: "Cuento de hadas.png" },
    { id: 3, nombre: "La dama de negro", editorial: "Edhasa", resumen: "Viajar a un remoto pueblo rodeado de marismas brumosas para asistir al entierro de una anciana no parece un plan muy interesante. Pero nada permite al joven y ambicioso abogado Arthur Kipps atisbar siquiera lo que semejante encargo profesional le puede deparar...", ISBN: "978-987-628-150-8", imagen: "La dama de negro.png" },
    { id: 4, nombre: "Hasta que te vuelva a ver", editorial: "Plaza & Janes", resumen: "Una apasionante novela coral de dos familias que unirán para siempre sus destinos, por sobre los escombros que dejó la guerra, las pasiones prohibidas, las mentiras y el miedo.", ISBN: "978-950-644-567-6", imagen: "Hasta que te vuelva a ver.png" },
    { id: 5, nombre: "Chica uno", editorial: "Ediciones B", resumen: "Pudiste escapar una vez, pero no podrás escapar siempre... Convertida en un fenómeno internacional y calificada de obra maestra por la crítica literaria, esta novela hipnótica, llena de misterios y personajes que no son lo que parecen, eleva el thriller psicológico a un nuevo nivel.", ISBN: "978-987-780-236-8", imagen: "Chica uno.png" },
    { id: 6, nombre: "Una familia no tan feliz", editorial: "Suma de Letras", resumen: "El nuevo y adictivo thriller de la autora de La pareja de al lado . En esta familia todos guardan secretos... incluso los muertos.", ISBN: "978-987-739-180-0", imagen: "Una familia no tan feliz.png" },
    { id: 7, nombre: "En el corazón del bosque", editorial: "UMBRIEL", resumen: "En el corazón del bosque es una novela desgarradora y evocadora, inspirada en historias reales de supervivencia durante la Segunda Guerra Mundial. Tras haber sido robada a su acomodada familia alemana y haber sido criada en la implacable naturaleza de Europa del Este, la joven Yona se encuentra sola en 1941 tras la muerte de su secuestradora. Sin embargo, su solitaria existencia se ve interrumpida cuando se cruza con un grupo de judíos que huyen del terror nazi. Ella se sorprende al descubrir lo que está sucediendo en el mundo, por lo que se compromet", ISBN: "978-987-8945-32-3", imagen: "En el corazón del bosque.png" },
    { id: 8, nombre: "La maldición de los sueños", editorial: "PUCK", resumen: "Rebecca Ross nos trae una historia sobre magia, venganza y el poder cautivador de los sueños. El reino de Azenor está invadido por una maldición desde hace años.", ISBN: "978-987-4132-99-4", imagen: "La maldición de los sueños.png" },
    { id: 9, nombre: "El camino de los reyes", editorial: "Nova", resumen: "El camino de los reyes es el primer volumen de «El Archivo de las Tormentas», el resultado de más de una década de construcción y escritura de universos, convertido en una obra maestra de la fantasía contemporánea en diez volúmenes. Con ella, Brandon Sanderson se postula como el autor del género que más lectores está ganando en todo el mundo.", ISBN: "978-84-666-5766-2", imagen: "El camino de los reyes.png" },
    { id: 10, nombre: "Palabras radiantes", editorial: "Nova", resumen: "La aclamada continuación de El camino de los reyes es, como el primer volumen de «El Archivo de las Tormentas», el resultado de más de una década de construcción y escritura de universos, convertida en una obra maestra de la fantasía contemporánea en diez volúmenes. Brandon Sa nderson se postula con ella como el autor del género que más lectores está ganando en todo el mundo.", ISBN: "978-84-666-5754-9", imagen: "Palabras radiantes.png" },
    { id: 11, nombre: "Juramentada", editorial: "Nova", resumen: "Juramentada es la aclamada continuación de El camino de los reyes y de Palabras radiantes , y tercera parte de la decalogía «El Archivo de las Tormentas», obra maestra de la fantasía épica que ha coronado la lista de best sellers de The New York Times y ha postulado a Sanderson como el autor de género que más lectores está ganando en todo el mundo.", ISBN: "978-84-17347-00-0", imagen: "Juramentada.png" },
    { id: 12, nombre: "El ritmo de la guerra", editorial: "Nova", resumen: "Brandon Sanderson nos reta a publicar su libro más esperado dos días después de su lanzamiento estadounidense", ISBN: "978-84-17347-93-2", imagen: "El ritmo de la guerra.png" },    
]

const guardarLibrosLS = (libros) => {
    localStorage.setItem("libros", JSON.stringify(libros));
}

const cargarLibrosLS = () => {
    return JSON.parse(localStorage.getItem("libros")) || [];
}

guardarLibrosLS(libros);